In [1]:
import pandas as pd

0.9090909090909091

In [35]:
a= pd.date_range(start='1/1/2024', end='10/10/2024', freq='D')
time_stamp=[]
for i in a:
    if i.month//10<=0 and i.day//10<=0:
        a=str(0)+str(i.month); b='0'+str(i.day)
    elif i.day//10<=0 and i.day//10>=0:
        b='0'+str(i.day); b=str(i.day)
    elif i.day//10>=0 and i.day//10<=0:
        a=str(i.month); b='0'+str(i.day)
    elif i.day//10>=0 and i.day//10>=0:
        a=str(i.month); b=str(i.day)
    time_stamp.append('2024'+a+b)
print(time_stamp)

['20240101', '20240102', '20240103', '20240104', '20240105', '20240106', '20240107', '20240108', '20240109', '2024110', '2024111', '2024112', '2024113', '2024114', '2024115', '2024116', '2024117', '2024118', '2024119', '2024120', '2024121', '2024122', '2024123', '2024124', '2024125', '2024126', '2024127', '2024128', '2024129', '2024130', '2024131', '20240201', '20240202', '20240203', '20240204', '20240205', '20240206', '20240207', '20240208', '20240209', '2024210', '2024211', '2024212', '2024213', '2024214', '2024215', '2024216', '2024217', '2024218', '2024219', '2024220', '2024221', '2024222', '2024223', '2024224', '2024225', '2024226', '2024227', '2024228', '2024229', '20240301', '20240302', '20240303', '20240304', '20240305', '20240306', '20240307', '20240308', '20240309', '2024310', '2024311', '2024312', '2024313', '2024314', '2024315', '2024316', '2024317', '2024318', '2024319', '2024320', '2024321', '2024322', '2024323', '2024324', '2024325', '2024326', '2024327', '2024328', '2024329', '2024330', '2024331', '20240401', '20240402', '20240403', '20240404', '20240405', '20240406', '20240407', '20240408', '20240409', '2024410', '2024411', '2024412', '2024413', '2024414', '2024415', '2024416', '2024417', '2024418', '2024419', '2024420', '2024421', '2024422', '2024423', '2024424', '2024425', '2024426', '2024427', '2024428', '2024429', '2024430', '20240501', '20240502', '20240503', '20240504', '20240505', '20240506', '20240507', '20240508', '20240509', '2024510', '2024511', '2024512', '2024513', '2024514', '2024515', '2024516', '2024517', '2024518', '2024519', '2024520', '2024521', '2024522', '2024523', '2024524', '2024525', '2024526', '2024527', '2024528', '2024529', '2024530', '2024531', '20240601', '20240602', '20240603', '20240604', '20240605', '20240606', '20240607', '20240608', '20240609', '2024610', '2024611', '2024612', '2024613', '2024614', '2024615', '2024616', '2024617', '2024618', '2024619', '2024620', '2024621', '2024622', '2024623', '2024624', '2024625', '2024626', '2024627', '2024628', '2024629', '2024630', '20240701', '20240702', '20240703', '20240704', '20240705', '20240706', '20240707', '20240708', '20240709', '2024710', '2024711', '2024712', '2024713', '2024714', '2024715', '2024716', '2024717', '2024718', '2024719', '2024720', '2024721', '2024722', '2024723', '2024724', '2024725', '2024726', '2024727', '2024728', '2024729', '2024730', '2024731', '20240801', '20240802', '20240803', '20240804', '20240805', '20240806', '20240807', '20240808', '20240809', '2024810', '2024811', '2024812', '2024813', '2024814', '2024815', '2024816', '2024817', '2024818', '2024819', '2024820', '2024821', '2024822', '2024823', '2024824', '2024825', '2024826', '2024827', '2024828', '2024829', '2024830', '2024831', '20240901', '20240902', '20240903', '20240904', '20240905', '20240906', '20240907', '20240908', '20240909', '2024910', '2024911', '2024912', '2024913', '2024914', '2024915', '2024916', '2024917', '2024918', '2024919', '2024920', '2024921', '2024922', '2024923', '2024924', '2024925', '2024926', '2024927', '2024928', '2024929', '2024930', '202491', '202492', '202493', '202494', '202495', '202496', '202497', '202498', '202499', '20241010']

In [57]:
time_list=[]
for a in range(273):
    time_list.append(pd.Timestamp(19723+a, unit="D").strftime("%Y%m%d"))

print(len(time_list))

273

In [55]:
19996-19723

273